# encoding: utf-8
Karuta.create(:kazin => "天智天皇",
              :uta => "秋の田の　かりほの庵の　苫をあらみ　わが衣手は　露にぬれつつ",
              :yomi => "akinotano karihonoihono tomawoarami wagakoromodeha tuyuninuretutu")
Karuta.create(:kazin => "持統天皇",
              :uta => "春すぎて　夏来にけらし　白妙の　衣ほすてふ　天の香具山",
              :yomi => "harusugite natukinikerasi sirotaheno koromohosutehu amanokaguyama")
Karuta.create(:kazin => "柿本人麻呂", 
              :uta => "あしびきの　山鳥の尾の　しだり尾の　ながながし夜を　ひとりかも寝む", 
              :yomi => "asibikino yamadorinoono sidariono naganagasiyowo hitorikamonemu")
Karuta.create(:kazin => "山部赤人", 
              :uta => "田子の浦に　うち出でてみれば　白妙の　富士の高嶺に　雪は降りつつ", 
              :yomi => "tagonourani utiidetemireba sirotaheno huzinotakaneni yukihahuritutu")
Karuta.create(:kazin => "猿丸大夫", 
              :uta => "奥山に　紅葉踏みわけ　鳴く鹿の　声きく時ぞ　秋は悲しき", 
              :yomi => "okuyamani momidihumiwake nakusikano koekikutokizo akihakanasiki")
Karuta.create(:kazin => "中納言家持", 
              :uta => "かささぎの　渡せる橋に　おく霜の　白きをみれば　夜ぞふけにける", 
              :yomi => "kasasagino wataseruhasini okusimono sirokiwomireba yozohukenikeru")
Karuta.create(:kazin => "安倍仲麿", 
              :uta => "天の原　ふりさけ見れば　春日なる　三笠の山に　出でし月かも", 
              :yomi => "amanohara hurisakemireba kasuganaru mikasanoyamani idesitukikamo")
Karuta.create(:kazin => "喜撰法師", 
              :uta => "わが庵は　都のたつみ　しかぞすむ　世をうぢ山と　人はいふなり", 
              :yomi => "wagaihoha miyakonotatumi sikazosumu yowoudiyamato hitohaihunari")
Karuta.create(:kazin => "小野小町", 
              :uta => "花の色は　うつりにけりな　いたづらに　わが身世にふる　ながめせしまに", 
              :yomi => "hananoiroha uturinikerina itadurani wagamiyonihuru nagamesesimani")
Karuta.create(:kazin => "蝉丸", 
              :uta => "これやこの　行くも帰るも　別れては　知るも知らぬも　逢坂の関", 
              :yomi => "koreyakono yukumokaherumo wakareteha sirumosiranumo ahusakanoseki")
Karuta.create(:kazin => "参議篁", 
              :uta => "わたの原　八十島かけて　漕ぎ出でぬと　人には告げよ　海人の釣舟", 
              :yomi => "watanohara yasosimakakete kogiidenuto hitonihatugeyo amanoturibune")
Karuta.create(:kazin => "僧正遍照", 
              :uta => "天つ風　雲の通ひ路　吹き閉ぢよ　をとめの姿　しばしとどめむ", 
              :yomi => "amatukaze kumonokayohidi hukitodiyo wotomenosugata sibasitodomemu")
Karuta.create(:kazin => "陽成院", 
              :uta => "筑波嶺の　峰より落つる　男女川　恋ぞつもりて　淵となりぬる", 
              :yomi => "tukubaneno mineyorioturu minanogaha kohizotumorite hutitonarinuru")
Karuta.create(:kazin => "河原左大臣", 
              :uta => "陸奥の　しのぶもぢずり　誰ゆゑに　乱れそめにし　われならなくに", 
              :yomi => "mitinokuno sinobumodizuri tareyueni midaresomenisi warenaranakuni")
Karuta.create(:kazin => "光孝天皇", 
              :uta => "君がため　春の野に出でて　若菜つむ　わが衣手に　雪は降りつつ", 
              :yomi => "kimigatame harunononiidete wakanatumu wagakoromodeni yukihahuritutu")
Karuta.create(:kazin => "中納言行平", 
              :uta => "たち別れ　いなばの山の　峰に生ふる　まつとし聞かば　今帰り来む", 
              :yomi => "tatiwakare inabanoyamano mineniohuru matutosikikaba imakaerikomu")
Karuta.create(:kazin => "在原業平朝臣", 
              :uta => "ちはやぶる　神代も聞かず　竜田川　からくれなゐに　水くくるとは", 
              :yomi => "tihayaburu kamiyomokikazu tatutagaha karakurenaini midukukurutoha")
Karuta.create(:kazin => "藤原敏行朝臣",
              :uta => "住の江の　岸による波　よるさへや　夢の通ひ路　人めよくらむ ",
              :yomi => "suminoeno kisiniyorunami yorusaheya yumenokayohidi hitomeyokuramu")
Karuta.create(:kazin => "伊勢",
              :uta => "難波潟　みじかき芦の　ふしの間も　逢はでこの世を　過ぐしてよとや",
              :yomi => "nanihagata mizikakiasino husinomamo ahadekonoyowo sugusiteyotoya")
Karuta.create(:kazin => "元良親王",
              :uta => "わびぬれば　今はた同じ　難波なる　みをつくしても　逢はむとぞ思ふ",
              :yomi => "wabinureba imahataonazi nanihanaru miwotukusitemo ahamutozoomohu")
Karuta.create(:kazin => "素性法師",
              :uta => "今来むと　言ひしばかりに　長月の　有明の月を　待ち出でつるかな",
              :yomi => "imakomuto ihisibakarini nagatukino ariakenotukiwo matiideturukana")
Karuta.create(:kazin => "文屋康秀",
              :uta => "吹くからに　秋の草木の　しをるれば　むべ山風を　嵐といふらむ",
              :yomi => "hukukarani akinokusakino siworureba mubeyamakazewo arasitoihuramu")
Karuta.create(:kazin => "大江千里",
              :uta => "月見れば　ちぢにものこそ　悲しけれ　わが身一つの　秋にはあらねど",
              :yomi => "tukimireba tidinimonokoso kanasikere wagamihitotuno akinihaaranedo")
Karuta.create(:kazin => "菅家",
              :uta => "このたびは　ぬさもとりあへず　手向山　紅葉の錦　神のまにまに",
              :yomi => "konotabiha nusamotoriahezu tamukeyama momidinonisiki kaminomanimani")
Karuta.create(:kazin => "三条右大臣",
              :uta => "名にしおはば　逢坂山の　さねかづら　人にしられで　くるよしもがな",
              :yomi => "nanisiohaba ahusakayamano sanekadura hitonisirarede kuruyosimogana")
Karuta.create(:kazin => "貞信公",
              :uta => "小倉山　峰のもみぢ葉　心あらば　今ひとたびの　みゆき待たなむ",
              :yomi => "wogurayama minenomomidiba kokoroaraba imahitotabino miyukimatanamu")
Karuta.create(:kazin => "中納言兼輔",
              :uta => "みかの原　わきて流るる　泉川　いつ見きとてか　恋しかるらむ",
              :yomi => "mikanohara wakitenagaruru idumigaha itumikitoteka kohisikaruramu")
Karuta.create(:kazin => "源宗于朝臣",
              :uta => "山里は　冬ぞさびしさ　まさりける　人目も草も　かれぬと思へば",
              :yomi => "yamazatoha huyuzosabisisa masarikeru hitomemokusamo karenutoomoheba")
Karuta.create(:kazin => "凡河内躬恒",
              :uta => "心あてに　折らばや折らむ　初霜の　置きまどはせる　白菊の花",
              :yomi => "kokoroateni orabayaoramu hatusimono okimadohaseru siragikunohana")
Karuta.create(:kazin => "壬生忠岑",
              :uta => "有明の　つれなく見えし　別れより　あかつきばかり　憂きものはなし",
              :yomi => "ariakeno turenakumiesi wakareyori akatukibakari ukimonohanasi")
Karuta.create(:kazin => "坂上是則",
              :uta => "朝ぼらけ　有明の月と　見るまでに　吉野の里に　降れる白雪",
              :yomi => "asaborake ariakenotukito mirumadeni yosinonosatoni hurerusirayuki")
Karuta.create(:kazin => "春道列樹",
              :uta => "山川に　風のかけたる　しがらみは　流れもあへぬ　紅葉なりけり",
              :yomi => "yamagahani kazenokaketaru sigaramiha nagaremoahenu momidinarikeri")
Karuta.create(:kazin => "紀友則",
              :uta => "ひさかたの　光のどけき　春の日に　静心なく　花の散るらむ",
              :yomi => "hisakatano hikarinodokeki harunohini sidugokoronaku hananotiruramu")
Karuta.create(:kazin => "藤原興風",
              :uta => "誰をかも　知る人にせむ　高砂の　松も昔の　友ならなくに",
              :yomi => "tarewokamo siruhitonisemu takasagono matumomukasino tomonaranakuni")
Karuta.create(:kazin => "紀貫之",
              :uta => "人はいさ　心も知らず　ふるさとは　花ぞ昔の　香ににほひける",
              :yomi => "hitohaisa kokoromosirazu hurusato hanazomukasino kaninihohikeru")
Karuta.create(:kazin => "清原深養父",
              :uta => "夏の夜は　まだ宵ながら　明けぬるを　雲のいづこに　月宿るらむ ",
              :yomi => "natunoyoha madayohinagara akenuruwo kumonoidukoni tukiyadoruramu")
Karuta.create(:kazin => "文屋朝康",
              :uta => "白露に　風の吹きしく　秋の野は　つらぬきとめぬ　玉ぞ散りける",
              :yomi => "siratuyuni kazenohukisiku akinonoha turanukitomenu tamazotirikeru")
Karuta.create(:kazin => "右近",
              :uta => "忘らるる　身をば思はず　誓ひてし　人の命の　惜しくもあるかな",
              :yomi => "wasuraruru miwobaomohazu tikahitesi hitonoinotino wosikumoarukana")
Karuta.create(:kazin => "参議等",
              :uta => "浅茅生の　小野の篠原　しのぶれど　あまりてなどか　人の恋しき ",
              :yomi => "asadihuno ononosinohara sinoburedo amaritenadoka hitonokohisiki")
Karuta.create(:kazin => "平兼盛",
              :uta => "しのぶれど　色に出でにけり　わが恋は　物や思ふと　人の問ふまで",
              :yomi => "sinoburedo ironiidenikeri wagakohiha monoyaomohuto hitonotohumade")
Karuta.create(:kazin => "壬生忠見",
              :uta => "恋すてふ　わが名はまだき　立ちにけり　人知れずこそ　思ひそめしか",
              :yomi => "kohisutehu waganahamadaki tatinikeri hitosirezukoso omohisomesika")
Karuta.create(:kazin => "清原元輔",
              :uta => "契りきな　かたみに袖を　しぼりつつ　末の松山　波越さじとは",
              :yomi => "tigirikina kataminisodewo siboritutu suenomatuyama namikosazitoba")
Karuta.create(:kazin => "権中納言敦忠",
              :uta => "逢ひ見ての　のちの心に　くらぶれば　昔は物を　思はざりけり",
              :yomi => "ahimiteno notinokokoroni kurabureba mukasihamonowo omohazarikeri")
Karuta.create(:kazin => "中納言朝忠",
              :uta => "逢ふことの　絶えてしなくは　なかなかに　人をも身をも　恨みざらまし",
              :yomi => "ahukotono taetesinakuha nakanakani hitowomomiwomo uramizaramasi")
Karuta.create(:kazin => "謙徳公",
              :uta => "あはれとも　いふべき人は　思ほえで　身のいたづらに　なりぬべきかな",
              :yomi => "aharetomo ihubekihitoha omohoede minoitadurani narinubekikana")
Karuta.create(:kazin => "曾禰好忠",
              :uta => "由良のとを　渡る舟人　かぢを絶え　ゆくへも知らぬ　恋の道かな ",
              :yomi => "yuranotowo wataruhunabito kadiwotae yukuhemosiranu kohinomitikana")
Karuta.create(:kazin => "恵慶法師",
              :uta => "八重葎　しげれる宿の　さびしきに　人こそ見えね　秋は来にけり",
              :yomi => "yahemugura sigereruyadono sabisikini hitokosomiene akihakinikeri")
Karuta.create(:kazin => "源重之",
              :uta => "風をいたみ　岩うつ波の　おのれのみ　くだけて物を　思ふころかな",
              :yomi => "kazewoitami iwautunamino onorenomi kudaketemonowo omohukorokana")
Karuta.create(:kazin => "大中臣能宣",
              :uta => "みかきもり　衛士のたく火の　夜は燃え　昼は消えつつ　物をこそ思へ",
              :yomi => "mikakimori ezinotakuhino yoruhamoe hiruhakietutu monowokosoomohe")
Karuta.create(:kazin => "藤原義孝",
              :uta => "君がため　惜しからざりし　命さへ　長くもがなと　思ひけるかな",
              :yomi => "kimigatame osikarazarisi inotisahe nagakumoganato omohikerukana")
Karuta.create(:kazin => "藤原実方朝臣",
              :uta => "かくとだに　えやはいぶきの　さしも草　さしも知らじな　燃ゆる思ひを",
              :yomi => "kakutodani eyahaibukino sasimokusa sasimosirazina moyuruomohiwo")
Karuta.create(:kazin => "藤原道信朝臣",
              :uta => "明けぬれば　暮るるものとは　知りながら　なほうらめしき　朝ぼらけかな",
              :yomi => "akenureba kururumonotoha sirinagara nahouramesiki asaborakekana")
Karuta.create(:kazin => "右大将道綱母",
              :uta => "嘆きつつ　ひとり寝る夜の　明くる間は　いかに久しき　ものとかは知る",
              :yomi => "nagekitutu hitorineruyono akurumaha ikanihisasiki monotokahasiru")
Karuta.create(:kazin => "儀同三司母",
              :uta => "忘れじの　行く末までは　かたければ　今日を限りの　命ともがな",
              :yomi => "wasurezino yukusuemadeha katakereba kehuwokagirino inotitomogana")
Karuta.create(:kazin => "大納言公任",
              :uta => "滝の音は　絶えて久しく　なりぬれど　名こそ流れて　なほ聞こえけれ",
              :yomi => "takinootoha taetehisasiku narinuredo nakosonagarete nahokikoekere")
Karuta.create(:kazin => "和泉式部",
              :uta => "あらざらむ　この世のほかの　思ひ出に　今ひとたびの　逢ふこともがな",
              :yomi => "arazaramu konoyonohokano omohideni imahitotabino ahukotomogana")
Karuta.create(:kazin => "紫式部",
              :uta => "めぐりあひて　見しやそれとも　わかぬ間に　雲がくれにし　夜半の月かな",
              :yomi => "meguriahite misiyasoretomo wakanumani kumogakurenisi yohanotukikana")
Karuta.create(:kazin => "大弐三位",
              :uta => "有馬山　猪名の笹原　風吹けば　いでそよ人を　忘れやはする",
              :yomi => "arimayama inanosasahara kazehukeba idesoyohitowo wasureyahasuru")
Karuta.create(:kazin => "赤染衛門",
              :uta => "やすらはで　寝なましものを　さ夜更けて　かたぶくまでの　月を見しかな",
              :yomi => "yasurahade nenamasimonowo sayohukete katabukumadeno tukiwomisikana")
Karuta.create(:kazin => "小式部内侍",
              :uta => "大江山　いく野の道の　遠ければ　まだふみもみず　天の橋立",
              :yomi => "ohoeyama ikunonomitino tookereba madahumimomizu amanohasidate")
Karuta.create(:kazin => "伊勢大輔",
              :uta => "いにしへの　奈良の都の　八重桜　けふ九重に　にほひぬるかな",
              :yomi => "inisiheno naranomiyakono yaezakura kehukokonoeni nihohinurukana")
Karuta.create(:kazin => "清少納言",
              :uta => "夜をこめて　鳥のそらねは　はかるとも　よに逢坂の　関はゆるさじ",
              :yomi => "yowokomete torinosoraneha hakarutomo yoniahusakano sekihayurusazi")
Karuta.create(:kazin => "左京大夫道雅",
              :uta => "今はただ　思ひ絶えなむ　とばかりを　人づてならで　言ふよしもがな",
              :yomi => "imahatada omohitaenamu tobakariwo hitodutenarade ihuyosimogana")
Karuta.create(:kazin => "権中納言定頼",
              :uta => "朝ぼらけ　宇治の川霧　たえだえに　あらはれわたる　瀬々の網代木",
              :yomi => "asaborake udinokahagiri taedaeni araharewataru sezenoazirogi")
Karuta.create(:kazin => "相模",
              :uta => "恨みわび　ほさぬ袖だに　あるものを　恋に朽ちなむ　名こそ惜しけれ",
              :yomi => "uramiwabi hosanusodedani arumonowo kohinikutinamu nakosowosikere")
Karuta.create(:kazin => "前大僧正行尊",
              :uta => "もろともに　あはれと思へ　山桜　花よりほかに　知る人もなし",
              :yomi => "morotomoni aharetoomohe yamazakura hanayorihokani siruhitomonasi")
Karuta.create(:kazin => "周防内侍",
              :uta => "春の夜の　夢ばかりなる　手枕に　かひなく立たむ　名こそ惜しけれ",
              :yomi => "harunoyono yumebakarinaru temakurani kahinakutatamu nakosoosikere")
Karuta.create(:kazin => "三条院",
              :uta => "心にも　あらでうき世に　ながらへば　恋しかるべき　夜半の月かな",
              :yomi => "kokoronimo aradeukiyoni nagaraheba kohisikarubeki yohanotukikana")
Karuta.create(:kazin => "能因法師",
              :uta => "嵐吹く　み室の山の　もみぢ葉は　竜田の川の　錦なりけり",
              :yomi => "arasihuku mimuronoyamano momidibaha tatutanokahano nisikinarikeri")
Karuta.create(:kazin => "良暹法師",
              :uta => "さびしさに　宿を立ち出でて　ながむれば　いづこも同じ　秋の夕暮れ",
              :yomi => "sabisisani yadowotatiidete nagamureba idukomoonazi akinoyuhugure")
Karuta.create(:kazin => "大納言経信",
              :uta => "夕されば　門田の稲葉　おとづれて　芦のまろやに　秋風ぞ吹く",
              :yomi => "yuhusareba kadotanoinaba otodurete asinomaroyani akikazezohuku")
Karuta.create(:kazin => "祐子内親王家紀伊",
              :uta => "音に聞く　高師の浜の　あだ波は　かけじや袖の　ぬれもこそすれ",
              :yomi => "otonikiku takasinohamano adanamiha kakeziyasodeno nuremokososure")
Karuta.create(:kazin => "権中納言匡房",
              :uta => "高砂の　尾の上の桜　咲きにけり　外山の霞　立たずもあらなむ",
              :yomi => "takasagono onouenosakura sakinikeri toyamanokasumi tatazumoaranamu")
Karuta.create(:kazin => "源俊頼朝臣",
              :uta => "憂かりける　人を初瀬の　山おろしよ　はげしかれとは　祈らぬものを",
              :yomi => "ukarikeru hitowohatuseno yamaorosiyo hagesikaretoha inoranumonowo")
Karuta.create(:kazin => "藤原基俊",
              :uta => "契りおきし　させもが露を　命にて　あはれ今年の　秋もいぬめり ",
              :yomi => "tigiriokisi sasemogatuyuwo inotinite aharekotosino akimoinumeri")
Karuta.create(:kazin => "法性寺入道前関白太政大臣",
              :uta => "わたの原　漕ぎ出でて見れば　ひさかたの　雲居にまがふ　沖つ白波",
              :yomi => "watanohara kogiidetemireba hisakatano kumoinimagahu okitusiranami")
Karuta.create(:kazin => "崇徳院",
              :uta => "瀬をはやみ　岩にせかるる　滝川の　われても末に　あはむとぞ思ふ",
              :yomi => "sewohayami iwanisekaruru takigawano waretemosueni ahamutozoomohu")
Karuta.create(:kazin => "源兼昌",
              :uta => "淡路島　かよふ千鳥の　鳴く声に　いく夜寝覚めぬ　須磨の関守 ",
              :yomi => "ahadisima kayohutidorino nakukoeni ikuyonezamenu sumanosekimori")
Karuta.create(:kazin => "左京大夫顕輔",
              :uta => "秋風に　たなびく雲の　絶え間より　もれ出づる月の　影のさやけさ  ",
              :yomi => "akikazeni tanabikukumono taemayori moreidurutukino kagenosayakesa")
Karuta.create(:kazin => "待賢門院堀河",
              :uta => "長からむ　心も知らず　黒髪の　乱れて今朝は　物をこそ思へ",
              :yomi => "nagakaramu kokoromosirazu kurokamino midaretekesaha monowokosoomohe")
Karuta.create(:kazin => "後徳大寺左大臣",
              :uta => "ほととぎす　鳴きつる方を　ながむれば　ただ有明の　月ぞ残れる",
              :yomi => "hototogisu nakiturukatawo nagamureba tadaariakeno tukizonokoreru")
Karuta.create(:kazin => "道因法師",
              :uta => "思ひわび　さても命は　あるものを　憂きにたへぬは　涙なりけり",
              :yomi => "omohiwabi satemoinotiha arumonowo ukinitahenuha namidanarikeri")
Karuta.create(:kazin => "皇太后宮大夫俊成",
              :uta => "世の中よ　道こそなけれ　思ひ入る　山の奥にも　鹿ぞ鳴くなる ",
              :yomi => "yononakayo mitikosonakere omohiiru yamanookunimo sikazonakunaru")
Karuta.create(:kazin => "藤原清輔朝臣",
              :uta => "長らへば　またこのごろや　しのばれむ　憂しと見し世ぞ　今は恋しき",
              :yomi => "nagaraheba matakonogoroya sinobaremu usitomisiyozo imahakohisiki")
Karuta.create(:kazin => "俊恵法師",
              :uta => "夜もすがら　物思ふころは　明けやらで　閨のひまさへ　つれなかりけり",
              :yomi => "yomosugara monoomohukoroha akeyarade neyanohimasahe turenakarikeri")
Karuta.create(:kazin => "西行法師",
              :uta => "嘆けとて　月やは物を　思はする　かこち顔なる　わが涙かな",
              :yomi => "nageketote tukiyahamonowo omohasuru kakotigahonaru waganamidakana")
Karuta.create(:kazin => "寂蓮法師",
              :uta => "村雨の　露もまだひぬ　真木の葉に　霧立ちのぼる　秋の夕暮れ",
              :yomi => "murasameno tuyumomadahinu makinohani kiritatinoboru akinoyuhugure")
Karuta.create(:kazin => "皇嘉門院別当",
              :uta => "難波江の　芦のかりねの　ひとよゆゑ　みをつくしてや　恋ひわたるべき",
              :yomi => "nanihaeno asinokarineno hitoyoyue miwotukusiteya kohiwatarubeki")
Karuta.create(:kazin => "式子内親王",
              :uta => "玉の緒よ　絶えなば絶えね　ながらへば　忍ぶることの　よわりもぞする",
              :yomi => "tamanooyo taenabataene nagaraheba sinoburukotono yowarimozosuru")
Karuta.create(:kazin => "殷富門院大輔",
              :uta => "見せばやな　雄島のあまの　袖だにも　ぬれにぞぬれし　色はかはらず",
              :yomi => "misebayana osimanoamano sodedanimo nurenizonuresi irohakaharazu")
Karuta.create(:kazin => "後京極摂政前太政大臣",
              :uta => "きりぎりす　鳴くや霜夜の　さむしろに　衣かたしき　ひとりかも寝む",
              :yomi => "kirigirisu nakuyasimoyono samusironi koromokatasiki hitorikamonemu")
Karuta.create(:kazin => "二条院讃岐",
              :uta => "わが袖は　潮干に見えぬ　沖の石の　人こそ知らね　かわく間もなし",
              :yomi => "wagasodeha sihohinimienu okinoisino hitokososirane kawakumamonasi")
Karuta.create(:kazin => "鎌倉右大臣",
              :uta => "世の中は　常にもがもな　渚こぐ　あまの小舟の　綱手かなしも",
              :yomi => "yononakaha tunenimogamona nagisakogu amanowobuneno tunadekanasimo")
Karuta.create(:kazin => "参議雅経",
              :uta => "み吉野の　山の秋風　さ夜更けて　ふるさと寒く　衣うつなり",
              :yomi => "miyosinono yamanoakikaze sayohukete hurusatosamuku koromoutunari")
Karuta.create(:kazin => "前大僧正慈円",
              :uta => "おほけなく　うき世の民に　おほふかな　わが立つ杣に　墨染の袖",
              :yomi => "ohokenaku ukiyonotamini ohohukana wagatatusomani sumizomenosode")
Karuta.create(:kazin => "入道前太政大臣",
              :uta => "花さそふ　嵐の庭の　雪ならで　ふりゆくものは　わが身なりけり",
              :yomi => "hanasasohu arasinoniwano yukinarade huriyukumonoha wagaminarikeri")
Karuta.create(:kazin => "権中納言定家",
              :uta => "来ぬ人を　まつほの浦の　夕なぎに　焼くや藻塩の　身もこがれつつ",
              :yomi => "konuhitowo matuhonourano yuhunagini yakuyamosihono mimokogaretutu")
Karuta.create(:kazin => "従二位家隆",
              :uta => "風そよぐ　ならの小川の　夕暮れは　みそぎぞ夏の　しるしなりける",
              :yomi => "kazesoyogu naranoogawano yuhugureha misogizonatuno sirusinarikeru")
Karuta.create(:kazin => "後鳥羽院",
              :uta => "人も惜し　人も恨めし　あぢきなく　世を思ふゆゑに　物思ふ身は",
              :yomi => "hitomowosi hitomouramesi adikinaku yowoomohuyueni monoomohumiha")
Karuta.create(:kazin => "順徳院",
              :uta => "ももしきや　古き軒端の　しのぶにも　なほあまりある　昔なりけり ",
              :yomi => "momosikiya hurukinokihano sinobunimo nahoamariaru mukasinarikeri")



